version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fin_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=fin_data
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ./financial:/app/financial

volumes:
  db-data:
